### ISSUE TITLE
Does this project include CutQC？Can you provide a complete sample program？thansks

### ISSUE THREAD

**Issue by NicolasYL** [weiT1993/simulator_benchmarks#1]
Recently I am studying the paper CutQC, but encountered a lot of difficulties, all the questions come from the picture below
![2020-12-17_165023](https://user-images.githubusercontent.com/47812418/105151999-9f630280-5b41-11eb-8db7-b0eca8a61924.png)
I know what the symbol represents by arXiv:1904.00102, but I don’t understand how to initialize the quantum state through the density matrix, what exactly the 8 sub-circuits refer to , and most importantly how to combine the 8 results to get the original circuit output
Can you help me solve these problems, thank you very much

**Comment by weiT1993** [comment]
Hi, this project does not include CutQC. CutQC is publicly available here: https://zenodo.org/record/4329804#.YBgfCy1h0Tt.

**Comment by NicolasYL** [comment]
Thank you and wish you a happy new year
